### Get all products
GET http://127.0.0.1:8888/products

###


### Create product
POST http://127.0.0.1:8888/products
Content-Type: application/json

{
  "name": "Milk",
  "price": 100
}

###


### Get product by id
GET http://127.0.0.1:8888/products/12

###


### Update product by id
PUT http://127.0.0.1:8888/products/12
Content-Type: application/json

{
  "name": "Milk",
  "price": 102
}

###


### Delete product by id
DELETE http://127.0.0.1:8888/products/13

###


### Get all orders
GET http://127.0.0.1:8888/orders

###


### Create order
POST http://127.0.0.1:8888/orders
Content-Type: application/json

{
  "product_id": 24,
  "quantity": 2
}

###


### Get order by id
GET http://127.0.0.1:8888/orders/1

###


### Delete order by id
DELETE http://127.0.0.1:8888/orders/1

###

